# TCL File Generated by Component Editor 18.1
# Tue Nov 05 12:54:24 CET 2024
# DO NOT MODIFY


# 
# LCD_DMA_CTRL "LCD_DMA_CTRL" v1.2
#  2024.11.05.12:54:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD_DMA_CTRL
# 
set_module_property DESCRIPTION ""
set_module_property NAME LCD_DMA_CTRL
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LCD_DMA_CTRL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DMA_LCD_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DMA_LCD_ctrl.vhd VHDL PATH ../VHDL_FILE/fichiers_etu/src/vhdl/LCD_ctrl/DMA_LCD_ctrl.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SIZEOFINT16 INTEGER 16
set_parameter_property SIZEOFINT16 DEFAULT_VALUE 16
set_parameter_property SIZEOFINT16 DISPLAY_NAME SIZEOFINT16
set_parameter_property SIZEOFINT16 TYPE INTEGER
set_parameter_property SIZEOFINT16 UNITS None
set_parameter_property SIZEOFINT16 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SIZEOFINT16 HDL_PARAMETER true
add_parameter SIZEOFINT32 INTEGER 32
set_parameter_property SIZEOFINT32 DEFAULT_VALUE 32
set_parameter_property SIZEOFINT32 DISPLAY_NAME SIZEOFINT32
set_parameter_property SIZEOFINT32 TYPE INTEGER
set_parameter_property SIZEOFINT32 UNITS None
set_parameter_property SIZEOFINT32 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SIZEOFINT32 HDL_PARAMETER true
add_parameter SIZEOFAVALONADD INTEGER 3
set_parameter_property SIZEOFAVALONADD DEFAULT_VALUE 3
set_parameter_property SIZEOFAVALONADD DISPLAY_NAME SIZEOFAVALONADD
set_parameter_property SIZEOFAVALONADD TYPE INTEGER
set_parameter_property SIZEOFAVALONADD UNITS None
set_parameter_property SIZEOFAVALONADD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SIZEOFAVALONADD HDL_PARAMETER true


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end LCD_D_C_n_o lcd_d_c_n Output 1
add_interface_port conduit_end LCD_WR_n_o lcd_wr_n Output 1
add_interface_port conduit_end LCD_data_o lcd_data Output sizeofint16


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_i reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avalon_cs_i chipselect Input 1
add_interface_port avalon_slave_0 avalon_wr_i write Input 1
add_interface_port avalon_slave_0 avalon_rd_i read Input 1
add_interface_port avalon_slave_0 avalon_read_data_o readdata Output sizeofint32
add_interface_port avalon_slave_0 avalon_address_i address Input sizeofavalonadd
add_interface_port avalon_slave_0 avalon_waitrequest_o waitrequest Output 1
add_interface_port avalon_slave_0 avalon_write_data_i writedata Input sizeofint32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address_o address Output sizeofint32
add_interface_port avalon_master master_read_o read Output 1
add_interface_port avalon_master master_readdata_i readdata Input sizeofint16
add_interface_port avalon_master master_waitrequest_i waitrequest Input 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avalon_slave_0
set_interface_property irq associatedClock clock_sink
set_interface_property irq associatedReset reset_sink
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq end_of_transaction_irq_o irq Output 1

